### PR TITLE
Add hack & test scripts

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- :gift: Initialize go module
- :gift: Add hack scripts
- :gift: Add test scripts
- :gift: Add Codecov config
- :gift: Add .gitignore
- :gift: Add Go lint config
- :gift: Add license file
- :gift: Add code of conduct file

### CODE REVIEW

**Review by rhuss — APPROVED** [review]
Thanks ! Let's get that merged and do the fine-tuning later.

/approve
/lgtm

**Comment by dsimansk** [comment]
@rhuss maybe we should bring in the owners and owners_aliases manually to play nicely with merge bot?

**Comment by rhuss** [comment]
> @rhuss maybe we should bring in the owners and owners_aliases manually to play nicely with merge bot?

Good point, let me try to remember how this is done :-)

**Pull request merged**
