### PR TITLE
:bug: Bubbletea initialization error handling

### LINKED ISSUE #165: `tui` pkg might SIGSEGV in some CI scenarios
As seen in [this build](https://github.com/wavesoftware/go-magetasks/actions/runs/8396102237/job/22996782606), in some CI scenarios, the `tui.Spinner` and `tui.Progress` code could panic with SIGSEGV (here [an extracted SIGSEGV goroutines dump](https://gist.github.com/cardil/a3b8f220bdbaf3c91c2a2fdf315342bf)). 

The `tui` package shouldn't panic with SIGSEGV, in case of initialization errors, due to lack of proper environment.

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Bubbletea initialization error handling
- :bug: Walk around for the charmbracelet/bubbletea#964 bug

/kind bug

Fixes #165 
Walkaround charmbracelet/bubbletea#964

**Release Note**

```release-note
UI initialization errors are not silenced
```

### CODE REVIEW

**Comment by cardil** [comment]
With those changes, the CI build for magetasks passes, see: https://github.com/wavesoftware/go-magetasks/actions/runs/8434810274/job/23098848334?pr=44#step:5:211

**Review by dsimansk — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
