### PR TITLE
Remove deprecated Serving API v1alpha1

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- Remove deprecated Serving API v1alpha1

A bit of clean up. It's also blocking auto-update PRs. 

/cc @rhuss

### CODE REVIEW

**Comment by rhuss** [comment]
What implication does this have wrt/ to backwards compatibility ? AFAIU it means that we don't support any installations that *only* knows about the v1alpha1 version, which should be fairly old anyways (not sure exactly until which version this was the case).

Technically the PR looks good to me.

**Comment by dsimansk** [comment]
> What implication does this have wrt/ to backwards compatibility ? AFAIU it means that we don't support any installations that _only_ knows about the v1alpha1 version, which should be fairly old anyways (not sure exactly until which version this was the case).
> 
> Technically the PR looks good to me.

It's being removed on Serving side in the next release (next week) current `main`. I can double check the details, but for a while now there was a conversion webhook converting `v1alpha1` to a newer API version anyway.

**Comment by dsimansk** [comment]
Well, it seems the API was there since `1.0` release. https://github.com/knative/serving/commit/5a51323d83e2b9dfccd8228e4f8604136831a902

**Comment by dsimansk** [comment]
> /approve /lgtm /hold
> 
> Maybe we can add the minimum version of Knative Serving that is now supported with the next kn, but I leave it to you.

Everything else is on `v1` currently wrt/ Serving APIs. Therefore we got pretty decent backward-comp coverage. Specifically `DomainMapping` CRUD won't work in combination of older kn and Serving v1.12+.

**Pull request merged**
